const WORDS = [
    {
        "ja": "一",
        "en": "one",
        "tr": "bir",
        "ar": "واحد",
        "arLatn": "wāḥid",
        "fa": "یک",
        "faLatn": "yek",
        "mn": "нэг",
        "mnIpa": "nek",
        "mnLatn": "nēg",
        "hi": "एक",
        "hiLatn": "ek"
    },
    {
        "ja": "二",
        "en": "two",
        "tr": "iki",
        "ar": "اثنان",
        "arLatn": "ithnān",
        "fa": "دو",
        "faLatn": "do",
        "mn": "хоёр",
        "mnIpa": "xɔjɐr",
        "mnLatn": "khoyor",
        "hi": "दो",
        "hiLatn": "do"
    },
    {
        "ja": "三",
        "en": "three",
        "tr": "üç",
        "ar": "ثلاثة",
        "arLatn": "thalātha",
        "fa": "سه",
        "faLatn": "se",
        "mn": "гурав",
        "mnIpa": "ɢʊrɐw",
        "mnLatn": "gurav",
        "hi": "तीन",
        "hiLatn": "tīn"
    },
    {
        "ja": "四",
        "en": "four",
        "tr": "dört",
        "ar": "أربعة",
        "arLatn": "arbaʿa",
        "fa": "چهار",
        "faLatn": "chahâr",
        "mn": "дөрөв",
        "mnIpa": "tɵrɵw",
        "mnLatn": "döröv",
        "hi": "चार",
        "hiLatn": "chār"
    },
    {
        "ja": "五",
        "en": "five",
        "tr": "beş",
        "ar": "خمسة",
        "arLatn": "khamsa",
        "fa": "پنج",
        "faLatn": "panj",
        "mn": "тав",
        "mnIpa": "tʰaw",
        "mnLatn": "tav",
        "hi": "पाँच",
        "hiLatn": "pā̃ch"
    },
    {
        "ja": "六",
        "en": "six",
        "tr": "altı",
        "ar": "ستة",
        "arLatn": "sitta",
        "fa": "شش",
        "faLatn": "shesh",
        "mn": "зургаа",
        "mnIpa": "dzʊrɢaː",
        "mnLatn": "zurgaa",
        "hi": "छह",
        "hiLatn": "chhah"
    },
    {
        "ja": "七",
        "en": "seven",
        "tr": "yedi",
        "ar": "سبعة",
        "arLatn": "sabʿa",
        "fa": "هفت",
        "faLatn": "haft",
        "mn": "долоо",
        "mnIpa": "tɔɮɔː",
        "mnLatn": "doloo",
        "hi": "सात",
        "hiLatn": "sāt"
    },
    {
        "ja": "八",
        "en": "eight",
        "tr": "sekiz",
        "ar": "ثمانية",
        "arLatn": "thamāniya",
        "fa": "هشت",
        "faLatn": "hasht",
        "mn": "найм",
        "mnIpa": "næːm",
        "mnLatn": "naim",
        "hi": "आठ",
        "hiLatn": "āṭh"
    },
    {
        "ja": "九",
        "en": "nine",
        "tr": "dokuz",
        "ar": "تسعة",
        "arLatn": "tisʿa",
        "fa": "نه",
        "faLatn": "noh",
        "mn": "ес",
        "mnIpa": "jɵs",
        "mnLatn": "yös",
        "hi": "नौ",
        "hiLatn": "nau"
    },
    {
        "ja": "十",
        "en": "ten",
        "tr": "on",
        "ar": "عشرة",
        "arLatn": "ʿashara",
        "fa": "ده",
        "faLatn": "dah",
        "mn": "арав",
        "mnIpa": "ɐrɐw",
        "mnLatn": "arav",
        "hi": "दस",
        "hiLatn": "das"
    },
    {
        "ja": "水",
        "en": "water",
        "tr": "su",
        "ar": "ماء",
        "arLatn": "māʾ",
        "fa": "آب",
        "faLatn": "âb",
        "mn": "ус",
        "mnIpa": "ʊs",
        "mnLatn": "us",
        "hi": "पानी",
        "hiLatn": "pānī"
    },
    {
        "ja": "火",
        "en": "fire",
        "tr": "ateş",
        "ar": "نار",
        "arLatn": "nār",
        "fa": "آتش",
        "faLatn": "âtash",
        "mn": "гал",
        "mnIpa": "ɢɐɮ",
        "mnLatn": "gal",
        "hi": "आग",
        "hiLatn": "āg"
    },
    {
        "ja": "太陽",
        "en": "sun",
        "tr": "güneş",
        "ar": "شمس",
        "arLatn": "shams",
        "fa": "خورشید",
        "faLatn": "xorshid",
        "mn": "нар",
        "mnIpa": "nɐr",
        "mnLatn": "nar",
        "hi": "सूरज",
        "hiLatn": "sūraj"
    },
    {
        "ja": "月",
        "en": "moon",
        "tr": "ay",
        "ar": "قمر",
        "arLatn": "qamar",
        "fa": "ماه",
        "faLatn": "mâh",
        "mn": "сар",
        "mnIpa": "sɐr",
        "mnLatn": "sar",
        "hi": "चाँद",
        "hiLatn": "chā̃d"
    },
    {
        "ja": "星",
        "en": "star",
        "tr": "yıldız",
        "ar": "نجم",
        "arLatn": "najm",
        "fa": "ستاره",
        "faLatn": "setâre",
        "mn": "од",
        "mnIpa": "ɔt",
        "mnLatn": "od",
        "hi": "तारा",
        "hiLatn": "tārā"
    },
    {
        "ja": "雨",
        "en": "rain",
        "tr": "yağmur",
        "ar": "مطر",
        "arLatn": "maṭar",
        "fa": "باران",
        "faLatn": "bârân",
        "mn": "бороо",
        "mnIpa": "pɔrɔː",
        "mnLatn": "boroo",
        "hi": "बारिश",
        "hiLatn": "bārish"
    },
    {
        "ja": "風",
        "en": "wind",
        "tr": "rüzgâr",
        "ar": "ريح",
        "arLatn": "rīḥ",
        "fa": "باد",
        "faLatn": "bâd",
        "mn": "салхи",
        "mnIpa": "sɐɮxʲ",
        "mnLatn": "salkhi",
        "hi": "हवा",
        "hiLatn": "havā"
    },
    {
        "ja": "雪",
        "en": "snow",
        "tr": "kar",
        "ar": "ثلج",
        "arLatn": "thalj",
        "fa": "برف",
        "faLatn": "barf",
        "mn": "цас",
        "mnIpa": "t͡sʰɐs",
        "mnLatn": "tsas",
        "hi": "बर्फ़",
        "hiLatn": "barf"
    },
    {
        "ja": "空",
        "en": "sky",
        "tr": "gökyüzü",
        "ar": "سماء",
        "arLatn": "samāʾ",
        "fa": "آسمان",
        "faLatn": "âsemân",
        "mn": "тэнгэр",
        "mnIpa": "tʰeŋɡer",
        "mnLatn": "tenger",
        "hi": "आसमान",
        "hiLatn": "āsmān"
    },
    {
        "ja": "木",
        "en": "tree",
        "tr": "ağaç",
        "ar": "شجرة",
        "arLatn": "shajara",
        "fa": "درخت",
        "faLatn": "deraxt",
        "mn": "мод",
        "mnIpa": "mɔt",
        "mnLatn": "mod",
        "hi": "पेड़",
        "hiLatn": "peṛ"
    },
    {
        "ja": "石",
        "en": "stone",
        "tr": "taş",
        "ar": "حجر",
        "arLatn": "ḥajar",
        "fa": "سنگ",
        "faLatn": "sang",
        "mn": "чулуу",
        "mnIpa": "t͡ʃʊɮʊː",
        "mnLatn": "chuluu",
        "hi": "पत्थर",
        "hiLatn": "patthar"
    },
    {
        "ja": "道",
        "en": "road",
        "tr": "yol",
        "ar": "طريق",
        "arLatn": "ṭarīq",
        "fa": "راه",
        "faLatn": "râh",
        "mn": "зам",
        "mnIpa": "dzɐm",
        "mnLatn": "zam",
        "hi": "रास्ता",
        "hiLatn": "rāstā"
    },
    {
        "ja": "山",
        "en": "mountain",
        "tr": "dağ",
        "ar": "جبل",
        "arLatn": "jabal",
        "fa": "کوه",
        "faLatn": "kuh",
        "mn": "уул",
        "mnIpa": "ʊːɮ",
        "mnLatn": "uul",
        "hi": "पहाड़",
        "hiLatn": "pahāṛ"
    },
    {
        "ja": "川",
        "en": "river",
        "tr": "nehir",
        "ar": "نهر",
        "arLatn": "nahr",
        "fa": "رودخانه",
        "faLatn": "rudxâne",
        "mn": "гол",
        "mnIpa": "ɢɔɮ",
        "mnLatn": "gol",
        "hi": "नदी",
        "hiLatn": "nadī"
    },
    {
        "ja": "海",
        "en": "sea",
        "tr": "deniz",
        "ar": "بحر",
        "arLatn": "baḥr",
        "fa": "دریا",
        "faLatn": "daryâ",
        "mn": "далай",
        "mnIpa": "tɐɮæː",
        "mnLatn": "dalai",
        "hi": "समुद्र",
        "hiLatn": "samudra"
    },
    {
        "ja": "魚",
        "en": "fish",
        "tr": "balık",
        "ar": "سمك",
        "arLatn": "samak",
        "fa": "ماهی",
        "faLatn": "mâhi",
        "mn": "загас",
        "mnIpa": "dzɐɢɐs",
        "mnLatn": "zagas",
        "hi": "मछली",
        "hiLatn": "machhlī"
    },
    {
        "ja": "鳥",
        "en": "bird",
        "tr": "kuş",
        "ar": "طائر",
        "arLatn": "ṭāʾir",
        "fa": "پرنده",
        "faLatn": "parande",
        "mn": "шувуу",
        "mnIpa": "ʃʊwʊː",
        "mnLatn": "shuvuu",
        "hi": "पक्षी",
        "hiLatn": "pakshī"
    },
    {
        "ja": "犬",
        "en": "dog",
        "tr": "köpek",
        "ar": "كلب",
        "arLatn": "kalb",
        "fa": "سگ",
        "faLatn": "sag",
        "mn": "нохой",
        "mnIpa": "nɔxɔe̯",
        "mnLatn": "nokhoi",
        "hi": "कुत्ता",
        "hiLatn": "kuttā"
    },
    {
        "ja": "猫",
        "en": "cat",
        "tr": "kedi",
        "ar": "قط",
        "arLatn": "qiṭṭ",
        "fa": "گربه",
        "faLatn": "gorbe",
        "mn": "муур",
        "mnIpa": "mʊːr",
        "mnLatn": "muur",
        "hi": "बिल्ली",
        "hiLatn": "billī"
    },
    {
        "ja": "人",
        "en": "person",
        "tr": "insan",
        "ar": "شخص",
        "arLatn": "shakhṣ",
        "fa": "شخص",
        "faLatn": "shaxs",
        "mn": "хүн",
        "mnIpa": "xʊŋ",
        "mnLatn": "khün",
        "hi": "व्यक्ति",
        "hiLatn": "vyakti"
    },
    {
        "ja": "子ども",
        "en": "child",
        "tr": "çocuk",
        "ar": "طفل",
        "arLatn": "ṭifl",
        "fa": "کودک",
        "faLatn": "kudak",
        "mn": "хүүхэд",
        "mnIpa": "xʊːxet",
        "mnLatn": "khüükhed",
        "hi": "बच्चा",
        "hiLatn": "bachchā"
    },
    {
        "ja": "母",
        "en": "mother",
        "tr": "anne",
        "ar": "أم",
        "arLatn": "umm",
        "fa": "مادر",
        "faLatn": "mâdar",
        "mn": "ээж",
        "mnIpa": "eːt͡ʃ",
        "mnLatn": "eej",
        "hi": "माँ",
        "hiLatn": "mā̃"
    },
    {
        "ja": "父",
        "en": "father",
        "tr": "baba",
        "ar": "أب",
        "arLatn": "ab",
        "fa": "پدر",
        "faLatn": "pedar",
        "mn": "аав",
        "mnIpa": "aːw",
        "mnLatn": "aav",
        "hi": "पिता",
        "hiLatn": "pitā"
    },
    {
        "ja": "男の人",
        "en": "man",
        "tr": "erkek",
        "ar": "رجل",
        "arLatn": "rajul",
        "fa": "مرد",
        "faLatn": "mard",
        "mn": "эрэгтэй хүн",
        "mnIpa": "erextæː xʊŋ",
        "mnLatn": "eregtei khün",
        "hi": "आदमी",
        "hiLatn": "ādmī"
    },
    {
        "ja": "女の人",
        "en": "woman",
        "tr": "kadın",
        "ar": "امرأة",
        "arLatn": "imraʾa",
        "fa": "زن",
        "faLatn": "zan",
        "mn": "эмэгтэй хүн",
        "mnIpa": "emextæː xʊŋ",
        "mnLatn": "emegtei khün",
        "hi": "औरत",
        "hiLatn": "aurat"
    },
    {
        "ja": "名前",
        "en": "name",
        "tr": "isim",
        "ar": "اسم",
        "arLatn": "ism",
        "fa": "نام",
        "faLatn": "nâm",
        "mn": "нэр",
        "mnIpa": "ner",
        "mnLatn": "ner",
        "hi": "नाम",
        "hiLatn": "nām"
    },
    {
        "ja": "目",
        "en": "eye",
        "tr": "göz",
        "ar": "عين",
        "arLatn": "ʿayn",
        "fa": "چشم",
        "faLatn": "cheshm",
        "mn": "нүд",
        "mnIpa": "nʊt",
        "mnLatn": "nüd",
        "hi": "आँख",
        "hiLatn": "ā̃kh"
    },
    {
        "ja": "耳",
        "en": "ear",
        "tr": "kulak",
        "ar": "أذن",
        "arLatn": "udhun",
        "fa": "گوش",
        "faLatn": "gush",
        "mn": "чих",
        "mnIpa": "t͡ʃʰix",
        "mnLatn": "chikh",
        "hi": "कान",
        "hiLatn": "kān"
    },
    {
        "ja": "鼻",
        "en": "nose",
        "tr": "burun",
        "ar": "أنف",
        "arLatn": "anf",
        "fa": "بینی",
        "faLatn": "bini",
        "mn": "хамар",
        "mnIpa": "xɐmɐr",
        "mnLatn": "khamar",
        "hi": "नाक",
        "hiLatn": "nāk"
    },
    {
        "ja": "口",
        "en": "mouth",
        "tr": "ağız",
        "ar": "فم",
        "arLatn": "fam",
        "fa": "دهان",
        "faLatn": "dahân",
        "mn": "ам",
        "mnIpa": "ɐm",
        "mnLatn": "am",
        "hi": "मुँह",
        "hiLatn": "mũh"
    },
    {
        "ja": "手",
        "en": "hand",
        "tr": "el",
        "ar": "يد",
        "arLatn": "yad",
        "fa": "دست",
        "faLatn": "dast",
        "mn": "гар",
        "mnIpa": "ɢɐr",
        "mnLatn": "gar",
        "hi": "हाथ",
        "hiLatn": "hāth"
    },
    {
        "ja": "足",
        "en": "foot",
        "tr": "ayak",
        "ar": "قدم",
        "arLatn": "qadam",
        "fa": "پا",
        "faLatn": "pâ",
        "mn": "хөл",
        "mnIpa": "xɵɮ",
        "mnLatn": "khöl",
        "hi": "पैर",
        "hiLatn": "pair"
    },
    {
        "ja": "頭",
        "en": "head",
        "tr": "baş",
        "ar": "رأس",
        "arLatn": "raʾs",
        "fa": "سر",
        "faLatn": "sar",
        "mn": "толгой",
        "mnIpa": "tɔɮɢɔe̯",
        "mnLatn": "tolgoi",
        "hi": "सिर",
        "hiLatn": "sir"
    },
    {
        "ja": "心臓・心",
        "en": "heart",
        "tr": "kalp",
        "ar": "قلب",
        "arLatn": "qalb",
        "fa": "قلب",
        "faLatn": "qalb",
        "mn": "зүрх",
        "mnIpa": "dzʊrx",
        "mnLatn": "zürkh",
        "hi": "दिल",
        "hiLatn": "dil"
    },
    {
        "ja": "家",
        "en": "house",
        "tr": "ev",
        "ar": "بيت",
        "arLatn": "bayt",
        "fa": "خانه",
        "faLatn": "xâne",
        "mn": "гэр",
        "mnIpa": "ɢer",
        "mnLatn": "ger",
        "hi": "घर",
        "hiLatn": "ghar"
    },
    {
        "ja": "学校",
        "en": "school",
        "tr": "okul",
        "ar": "مدرسة",
        "arLatn": "madrasa",
        "fa": "مدرسه",
        "faLatn": "madrese",
        "mn": "сургууль",
        "mnIpa": "sʊrɢʊːɮʲ",
        "mnLatn": "surguul'",
        "hi": "स्कूल",
        "hiLatn": "skūl"
    },
    {
        "ja": "部屋",
        "en": "room",
        "tr": "oda",
        "ar": "غرفة",
        "arLatn": "ghurfa",
        "fa": "اتاق",
        "faLatn": "otâq",
        "mn": "өрөө",
        "mnIpa": "ɵrɵː",
        "mnLatn": "öröö",
        "hi": "कमरा",
        "hiLatn": "kamrā"
    },
    {
        "ja": "食べ物",
        "en": "food",
        "tr": "yemek",
        "ar": "طعام",
        "arLatn": "ṭaʿām",
        "fa": "غذا",
        "faLatn": "qazâ",
        "mn": "хоол",
        "mnIpa": "xɔːɮ",
        "mnLatn": "khool",
        "hi": "खाना",
        "hiLatn": "khānā"
    },
    {
        "ja": "パン",
        "en": "bread",
        "tr": "ekmek",
        "ar": "خبز",
        "arLatn": "khubz",
        "fa": "نان",
        "faLatn": "nân",
        "mn": "талх",
        "mnIpa": "tʰɐɮx",
        "mnLatn": "talkh",
        "hi": "रोटी",
        "hiLatn": "roṭī"
    },
    {
        "ja": "米・ご飯",
        "en": "rice",
        "tr": "pirinç",
        "ar": "أرز",
        "arLatn": "aruzz",
        "fa": "برنج",
        "faLatn": "berenj",
        "mn": "будаа",
        "mnIpa": "pʊtɐː",
        "mnLatn": "budaa",
        "hi": "चावल",
        "hiLatn": "chāval"
    },
    {
        "ja": "肉",
        "en": "meat",
        "tr": "et",
        "ar": "لحم",
        "arLatn": "laḥm",
        "fa": "گوشت",
        "faLatn": "gusht",
        "mn": "мах",
        "mnIpa": "mɐx",
        "mnLatn": "makh",
        "hi": "मांस",
        "hiLatn": "mā̃s"
    },
    {
        "ja": "卵",
        "en": "egg",
        "tr": "yumurta",
        "ar": "بيضة",
        "arLatn": "bayḍa",
        "fa": "تخم‌مرغ",
        "faLatn": "toxm-e morq",
        "mn": "өндөг",
        "mnIpa": "ɵntɵk",
        "mnLatn": "öndög",
        "hi": "अंडा",
        "hiLatn": "aṇḍā"
    },
    {
        "ja": "塩",
        "en": "salt",
        "tr": "tuz",
        "ar": "ملح",
        "arLatn": "milḥ",
        "fa": "نمک",
        "faLatn": "namak",
        "mn": "давс",
        "mnIpa": "tɐws",
        "mnLatn": "davs",
        "hi": "नमक",
        "hiLatn": "namak"
    },
    {
        "ja": "お茶",
        "en": "tea",
        "tr": "çay",
        "ar": "شاي",
        "arLatn": "shāy",
        "fa": "چای",
        "faLatn": "chây",
        "mn": "цай",
        "mnIpa": "t͡sʰæː",
        "mnLatn": "tsai",
        "hi": "चाय",
        "hiLatn": "chāy"
    },
    {
        "ja": "コーヒー",
        "en": "coffee",
        "tr": "kahve",
        "ar": "قهوة",
        "arLatn": "qahwa",
        "fa": "قهوه",
        "faLatn": "qahve",
        "mn": "кофе",
        "mnIpa": "kɔfʲe",
        "mnLatn": "kofe",
        "hi": "कॉफ़ी",
        "hiLatn": "kŏfī"
    },
    {
        "ja": "今日",
        "en": "today",
        "tr": "bugün",
        "ar": "اليوم",
        "arLatn": "al-yawm",
        "fa": "امروز",
        "faLatn": "emruz",
        "mn": "өнөөдөр",
        "mnIpa": "ɵnɵːtɵr",
        "mnLatn": "önöödör",
        "hi": "आज",
        "hiLatn": "āj"
    },
    {
        "ja": "明日",
        "en": "tomorrow",
        "tr": "yarın",
        "ar": "غدا",
        "arLatn": "ghadan",
        "fa": "فردا",
        "faLatn": "fardâ",
        "mn": "маргааш",
        "mnIpa": "mɐrɢaːʃ",
        "mnLatn": "margaash",
        "hi": "कल",
        "hiLatn": "kal"
    },
    {
        "ja": "昨日",
        "en": "yesterday",
        "tr": "dün",
        "ar": "أمس",
        "arLatn": "ams",
        "fa": "دیروز",
        "faLatn": "diruz",
        "mn": "өчигдөр",
        "mnIpa": "ɵt͡ʃʰiktɵr",
        "mnLatn": "öchigdör",
        "hi": "कल",
        "hiLatn": "kal"
    },
    {
        "ja": "今",
        "en": "now",
        "tr": "şimdi",
        "ar": "الآن",
        "arLatn": "al-ān",
        "fa": "الان",
        "faLatn": "alân",
        "mn": "одоо",
        "mnIpa": "ɔtɔː",
        "mnLatn": "odoo",
        "hi": "अब",
        "hiLatn": "ab"
    },
    {
        "ja": "朝",
        "en": "morning",
        "tr": "sabah",
        "ar": "صباح",
        "arLatn": "ṣabāḥ",
        "fa": "صبح",
        "faLatn": "sobh",
        "mn": "өглөө",
        "mnIpa": "ɵkɮɵː",
        "mnLatn": "öglöö",
        "hi": "सुबह",
        "hiLatn": "subah"
    },
    {
        "ja": "夜",
        "en": "night",
        "tr": "gece",
        "ar": "ليل",
        "arLatn": "layl",
        "fa": "شب",
        "faLatn": "shab",
        "mn": "шөнө",
        "mnIpa": "ʃɵn",
        "mnLatn": "shönö",
        "hi": "रात",
        "hiLatn": "rāt"
    },
    {
        "ja": "日・昼",
        "en": "day",
        "tr": "gün",
        "ar": "نهار",
        "arLatn": "nahār",
        "fa": "روز",
        "faLatn": "ruz",
        "mn": "өдөр",
        "mnIpa": "ɵtɵr",
        "mnLatn": "ödör",
        "hi": "दिन",
        "hiLatn": "din"
    },
    {
        "ja": "年",
        "en": "year",
        "tr": "yıl",
        "ar": "سنة",
        "arLatn": "sana",
        "fa": "سال",
        "faLatn": "sâl",
        "mn": "жил",
        "mnIpa": "t͡ʃiɮ",
        "mnLatn": "jil",
        "hi": "साल",
        "hiLatn": "sāl"
    },
    {
        "ja": "時間",
        "en": "time",
        "tr": "zaman",
        "ar": "وقت",
        "arLatn": "waqt",
        "fa": "زمان",
        "faLatn": "zamân",
        "mn": "цаг",
        "mnIpa": "t͡sʰɐk",
        "mnLatn": "tsag",
        "hi": "समय",
        "hiLatn": "samay"
    },
    {
        "ja": "分",
        "en": "minute",
        "tr": "dakika",
        "ar": "دقيقة",
        "arLatn": "daqīqa",
        "fa": "دقیقه",
        "faLatn": "daqiqe",
        "mn": "минут",
        "mnIpa": "minʊt",
        "mnLatn": "minut",
        "hi": "मिनट",
        "hiLatn": "minaṭ"
    },
    {
        "ja": "お金",
        "en": "money",
        "tr": "para",
        "ar": "مال",
        "arLatn": "māl",
        "fa": "پول",
        "faLatn": "pul",
        "mn": "мөнгө",
        "mnIpa": "mɵŋk",
        "mnLatn": "möngö",
        "hi": "पैसा",
        "hiLatn": "paisā"
    },
    {
        "ja": "店",
        "en": "shop",
        "tr": "dükkân",
        "ar": "متجر",
        "arLatn": "matjar",
        "fa": "مغازه",
        "faLatn": "maqâze",
        "mn": "дэлгүүр",
        "mnIpa": "teɮɢʊːr",
        "mnLatn": "delgüür",
        "hi": "दुकान",
        "hiLatn": "dukān"
    },
    {
        "ja": "駅",
        "en": "station",
        "tr": "istasyon",
        "ar": "محطة",
        "arLatn": "maḥaṭṭa",
        "fa": "ایستگاه",
        "faLatn": "istgâh",
        "mn": "буудал",
        "mnIpa": "pʊːtɐɮ",
        "mnLatn": "buudal",
        "hi": "स्टेशन",
        "hiLatn": "sṭeshan"
    },
    {
        "ja": "電車",
        "en": "train",
        "tr": "tren",
        "ar": "قطار",
        "arLatn": "qiṭār",
        "fa": "قطار",
        "faLatn": "qatâr",
        "mn": "галт тэрэг",
        "mnIpa": "ɢɐɮtʰ tʰerek",
        "mnLatn": "galt tereg",
        "hi": "रेलगाड़ी",
        "hiLatn": "relgāṛī"
    },
    {
        "ja": "バス",
        "en": "bus",
        "tr": "otobüs",
        "ar": "حافلة",
        "arLatn": "ḥāfila",
        "fa": "اتوبوس",
        "faLatn": "otobus",
        "mn": "автобус",
        "mnIpa": "ɐwtɔpʊs",
        "mnLatn": "avtobus",
        "hi": "बस",
        "hiLatn": "bas"
    },
    {
        "ja": "車",
        "en": "car",
        "tr": "araba",
        "ar": "سيارة",
        "arLatn": "sayyāra",
        "fa": "ماشین",
        "faLatn": "mâshin",
        "mn": "машин",
        "mnIpa": "mɐʃin",
        "mnLatn": "mashin",
        "hi": "कार",
        "hiLatn": "kār"
    },
    {
        "ja": "自転車",
        "en": "bicycle",
        "tr": "bisiklet",
        "ar": "دراجة",
        "arLatn": "darrāja",
        "fa": "دوچرخه",
        "faLatn": "docharkhe",
        "mn": "дугуй",
        "mnIpa": "tʊɢʊe̯",
        "mnLatn": "dugui",
        "hi": "साइकिल",
        "hiLatn": "sāikil"
    },
    {
        "ja": "切符",
        "en": "ticket",
        "tr": "bilet",
        "ar": "تذكرة",
        "arLatn": "tadhkira",
        "fa": "بلیت",
        "faLatn": "belit",
        "mn": "тасалбар",
        "mnIpa": "tʰɐsɐɮpɐr",
        "mnLatn": "tasalbar",
        "hi": "टिकट",
        "hiLatn": "ṭikaṭ"
    },
    {
        "ja": "ホテル",
        "en": "hotel",
        "tr": "otel",
        "ar": "فندق",
        "arLatn": "funduq",
        "fa": "هتل",
        "faLatn": "hotel",
        "mn": "зочид буудал",
        "mnIpa": "dzɔt͡ʃʰit pʊːtɐɮ",
        "mnLatn": "zochid buudal",
        "hi": "होटल",
        "hiLatn": "hoṭal"
    },
    {
        "ja": "トイレ",
        "en": "toilet",
        "tr": "tuvalet",
        "ar": "مرحاض",
        "arLatn": "mirḥāḍ",
        "fa": "توالت",
        "faLatn": "toâlet",
        "mn": "бие засах газар",
        "mnIpa": "pije d͡zɐsɐx ɢɐdzɐr",
        "mnLatn": "biye zasakh gazar",
        "hi": "शौचालय",
        "hiLatn": "shauchālay"
    },
    {
        "ja": "病院",
        "en": "hospital",
        "tr": "hastane",
        "ar": "مستشفى",
        "arLatn": "mustashfā",
        "fa": "بیمارستان",
        "faLatn": "bimârestân",
        "mn": "эмнэлэг",
        "mnIpa": "emneɮek",
        "mnLatn": "emneleg",
        "hi": "अस्पताल",
        "hiLatn": "aspatāl"
    },
    {
        "ja": "医者",
        "en": "doctor",
        "tr": "doktor",
        "ar": "طبيب",
        "arLatn": "ṭabīb",
        "fa": "پزشک",
        "faLatn": "pezeshk",
        "mn": "эмч",
        "mnIpa": "emt͡ʃʰ",
        "mnLatn": "emch",
        "hi": "डॉक्टर",
        "hiLatn": "ḍŏkṭar"
    },
    {
        "ja": "薬",
        "en": "medicine",
        "tr": "ilaç",
        "ar": "دواء",
        "arLatn": "dawāʾ",
        "fa": "دارو",
        "faLatn": "dâru",
        "mn": "эм",
        "mnIpa": "em",
        "mnLatn": "em",
        "hi": "दवा",
        "hiLatn": "davā"
    },
    {
        "ja": "仕事",
        "en": "job",
        "tr": "iş",
        "ar": "عمل",
        "arLatn": "ʿamal",
        "fa": "کار",
        "faLatn": "kâr",
        "mn": "ажил",
        "mnIpa": "ɐt͡ʃiɮ",
        "mnLatn": "ajil",
        "hi": "काम",
        "hiLatn": "kām"
    },
    {
        "ja": "友だち",
        "en": "friend",
        "tr": "arkadaş",
        "ar": "صديق",
        "arLatn": "ṣadīq",
        "fa": "دوست",
        "faLatn": "dust",
        "mn": "найз",
        "mnIpa": "næːdz",
        "mnLatn": "naiz",
        "hi": "दोस्त",
        "hiLatn": "dost"
    },
    {
        "ja": "先生",
        "en": "teacher",
        "tr": "öğretmen",
        "ar": "معلم",
        "arLatn": "muʿallim",
        "fa": "معلم",
        "faLatn": "moallem",
        "mn": "багш",
        "mnIpa": "pɐkʃ",
        "mnLatn": "bagsh",
        "hi": "शिक्षक",
        "hiLatn": "shikshak"
    },
    {
        "ja": "学生",
        "en": "student",
        "tr": "öğrenci",
        "ar": "طالب",
        "arLatn": "ṭālib",
        "fa": "دانش‌آموز",
        "faLatn": "dânesh-âmuz",
        "mn": "сурагч",
        "mnIpa": "sʊrɐkt͡ʃʰ",
        "mnLatn": "suragch",
        "hi": "विद्यार्थी",
        "hiLatn": "vidyārthī"
    },
    {
        "ja": "本",
        "en": "book",
        "tr": "kitap",
        "ar": "كتاب",
        "arLatn": "kitāb",
        "fa": "کتاب",
        "faLatn": "ketâb",
        "mn": "ном",
        "mnIpa": "nɔm",
        "mnLatn": "nom",
        "hi": "किताब",
        "hiLatn": "kitāb"
    },
    {
        "ja": "紙",
        "en": "paper",
        "tr": "kâğıt",
        "ar": "ورق",
        "arLatn": "waraq",
        "fa": "کاغذ",
        "faLatn": "kâqaz",
        "mn": "цаас",
        "mnIpa": "t͡sʰaːs",
        "mnLatn": "tsaас",
        "hi": "कागज़",
        "hiLatn": "kāgaz"
    },
    {
        "ja": "ペン",
        "en": "pen",
        "tr": "kalem",
        "ar": "قلم",
        "arLatn": "qalam",
        "fa": "خودکار",
        "faLatn": "xodkâr",
        "mn": "үзэг",
        "mnIpa": "ʊdzek",
        "mnLatn": "üzeg",
        "hi": "कलम",
        "hiLatn": "kalam"
    },
    {
        "ja": "机",
        "en": "desk",
        "tr": "masa",
        "ar": "مكتب",
        "arLatn": "maktab",
        "fa": "میز",
        "faLatn": "miz",
        "mn": "ширээ",
        "mnIpa": "ʃireː",
        "mnLatn": "shiree",
        "hi": "मेज़",
        "hiLatn": "mez"
    },
    {
        "ja": "椅子",
        "en": "chair",
        "tr": "sandalye",
        "ar": "كرسي",
        "arLatn": "kursī",
        "fa": "صندلی",
        "faLatn": "sandali",
        "mn": "сандал",
        "mnIpa": "sɐntɐɮ",
        "mnLatn": "sandal",
        "hi": "कुर्सी",
        "hiLatn": "kursī"
    },
    {
        "ja": "ドア",
        "en": "door",
        "tr": "kapı",
        "ar": "باب",
        "arLatn": "bāb",
        "fa": "در",
        "faLatn": "dar",
        "mn": "хаалга",
        "mnIpa": "xaːɮɢɐ",
        "mnLatn": "khaalga",
        "hi": "दरवाज़ा",
        "hiLatn": "darvāzā"
    },
    {
        "ja": "窓",
        "en": "window",
        "tr": "pencere",
        "ar": "نافذة",
        "arLatn": "nāfidha",
        "fa": "پنجره",
        "faLatn": "panjere",
        "mn": "цонх",
        "mnIpa": "t͡sʰɔŋx",
        "mnLatn": "tsonkh",
        "hi": "खिड़की",
        "hiLatn": "khiṛkī"
    },
    {
        "ja": "服",
        "en": "clothes",
        "tr": "giysi",
        "ar": "ملابس",
        "arLatn": "malābis",
        "fa": "لباس",
        "faLatn": "lebâs",
        "mn": "хувцас",
        "mnIpa": "xʊwt͡sʰɐs",
        "mnLatn": "khuvtsas",
        "hi": "कपड़े",
        "hiLatn": "kapṛe"
    },
    {
        "ja": "靴",
        "en": "shoes",
        "tr": "ayakkabı",
        "ar": "حذاء",
        "arLatn": "ḥidhāʾ",
        "fa": "کفش",
        "faLatn": "kafsh",
        "mn": "гутал",
        "mnIpa": "ɢʊtɐɮ",
        "mnLatn": "gutal",
        "hi": "जूते",
        "hiLatn": "jūte"
    },
    {
        "ja": "鍵",
        "en": "key",
        "tr": "anahtar",
        "ar": "مفتاح",
        "arLatn": "miftāḥ",
        "fa": "کلید",
        "faLatn": "kelid",
        "mn": "түлхүүр",
        "mnIpa": "tʰʊɮxʊːr",
        "mnLatn": "tülkhüür",
        "hi": "चाबी",
        "hiLatn": "chābī"
    },
    {
        "ja": "かばん",
        "en": "bag",
        "tr": "çanta",
        "ar": "حقيبة",
        "arLatn": "ḥaqība",
        "fa": "کیف",
        "faLatn": "kif",
        "mn": "цүнх",
        "mnIpa": "t͡sʰʊŋx",
        "mnLatn": "tsünkh",
        "hi": "बैग",
        "hiLatn": "baig"
    },
    {
        "ja": "電話",
        "en": "phone",
        "tr": "telefon",
        "ar": "هاتف",
        "arLatn": "hātif",
        "fa": "تلفن",
        "faLatn": "telefon",
        "mn": "утас",
        "mnIpa": "ʊtɐs",
        "mnLatn": "utas",
        "hi": "फ़ोन",
        "hiLatn": "fon"
    },
    {
        "ja": "写真",
        "en": "photo",
        "tr": "fotoğraf",
        "ar": "صورة",
        "arLatn": "ṣūra",
        "fa": "عکس",
        "faLatn": "aks",
        "mn": "зураг",
        "mnIpa": "dzʊrɐk",
        "mnLatn": "zurag",
        "hi": "फ़ोटो",
        "hiLatn": "foṭo"
    }
];
